name: DDocker to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Launch Express WAS with pm2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.15.0]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.10.5
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Get PNPM cache directory
        id: pnpm-cache-dir
        run: |
          echo "::set-output name=dir::$(pnpm config get store-dir)"
      - uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: ${{ steps.pnpm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: pnpm install

      - name: Configure .env variables
        run: |
          echo "PORT=${{ secrets.PORT }}" >> .env.production
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env.production
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env.production
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env.production
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env.production
          echo "DB_SCHEMA=${{ secrets.DB_SCHEMA }}" >> .env.production
          echo "ORIGIN=${{ secrets.ORIGIN }}" >> .env.production
          echo "CREDENTIALS=${{ secrets.CREDENTIALS }}" >> .env.production
          echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> .env.production
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env.production
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env.production
          echo "GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}" >> .env.production
          echo "GOOGLE_UNLINK_URI=${{ secrets.GOOGLE_UNLINK_URI }}" >> .env.production
          echo "GOOGLE_TOKEN_URL=${{ secrets.GOOGLE_TOKEN_URL }}" >> .env.production
          echo "GOOGLE_USERINFO_URL=${{ secrets.GOOGLE_USERINFO_URL }}" >> .env.production
          echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env.production
          echo "KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }}" >> .env.production
          echo "KAKAO_UNLINK_URI=${{ secrets.KAKAO_UNLINK_URI }}" >> .env.production
          echo "KAKAO_TOKEN_URL=${{ secrets.KAKAO_TOKEN_URL }}" >> .env.production
          echo "KAKAO_USERINFO_URL=${{ secrets.KAKAO_USERINFO_URL }}" >> .env.production
          echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env.production
          echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env.production

      - name: Project running check
        run: pnpm prod & npx wait-on tcp:127.0.0.1:${{ secrets.PORT }} -t 120s

      - name: SSH deploy
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.AWS_SSH_HOST }}
          username: ${{ secrets.AWS_SSH_USERNAME }}
          password: ${{ secrets.AWS_SSH_PASSWORD }}
          port: 22
          script: |
            sudo su
            cd ~/DDocker_BE
            git pull origin main
            pnpm reload
